name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Compile datapack
      run: ./datapack-compile.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: datapack
        path: ./out/*
